extends: standard
plugins:
  - standard
env:
  browser: true
globals:
  angular: 1
  utils: 1
  Scope: 1
  Compile: 1
  Directive: 1
  Provide: 1
  Injector: 1
  NgController: 1
  NgBind: 1
  NgBindAttribute: 1
  NgBindProperty: 1
  NgOnEvent: 1
rules:
  semi:
    - 2
    - always
  space-before-function-paren:
    - 2
    - never
